name: Hello World

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: |
          echo "Hello, World"
      - name: Dime la fecha
        run: date
      - run: ls -l
