name: CI/CD Pipeline

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Run Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Run Tests
        run: npm run test
